name: PR-CYCLE

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop
      - release/*

env:
  EARTHLY_TOOL_VERSION: '0.8.15'
  IMAGE_NAME: "earthly-test:latest"
  COLUMNS: 300
  NO_COLOR: 1

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: DOCKER-CACHE
        id: DOCKER-CACHE
        uses: actions/cache@v4
        with:
          path: /tmp/saved-image.tar.gz
          key: ${{ runner.os }}-docker-images
      - uses: earthly/actions-setup@v1
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "v${{ env.EARTHLY_TOOL_VERSION }}"
      - uses: actions/checkout@v3
      - name: INSTALL
        run: earthly --ci +install
      - name: BUILD
        run: earthly --ci +build
      - name: BUILD-IMAGE
        run: |
          earthly --ci +build-image --IMAGE_NAME="$IMAGE_NAME"
          echo "$IMAGE_NAME"
          docker image ls
      - name: SAVE-IMAGE
        run: |
          docker image ls
          docker image save "$IMAGE_NAME" | gzip > /tmp/saved-image.tar.gz
          tar -zt -f /tmp/saved-image.tar.gz
  publish:
    needs: [ 'build' ]
    runs-on: ubuntu-22.04
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_ORG: ${{ vars.DOCKERHUB_ORG }}
    steps:
      - name: DOCKER-CACHE
        id: DOCKER-CACHE
        uses: actions/cache@v4
        with:
          path: /tmp/saved-image.tar.gz
          key: ${{ runner.os }}-docker-images
      - uses: earthly/actions-setup@v1
        with: 
          version: "v${{ env.EARTHLY_TOOL_VERSION }}"
      - uses: actions/checkout@v3
      - name: PUBLISH
        run: |
          ls -l /tmp/saved-image.tar.gz
          tar -zt -f /tmp/saved-image.tar.gz
          docker image load < /tmp/saved-image.tar.gz
          docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
          earthly --ci --push +publish-image --DOCKERHUB_ORG="$DOCKERHUB_ORG"
